"""Add approved column to Issuer

Revision ID: 5332f507b667
Revises: ec5dabed590a
Create Date: 2025-08-15 20:21:42.447674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5332f507b667'
down_revision = 'ec5dabed590a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issuer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_issuer_wallet_address'), type_='unique')
        batch_op.drop_column('wallet_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issuer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.VARCHAR(length=42), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_issuer_wallet_address'), ['wallet_address'])
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
