"""Add filename column to IssuedDocument

Revision ID: 807d5cd2e2aa
Revises: 9966fd8817c6
Create Date: 2025-08-07 14:54:02.309535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807d5cd2e2aa'
down_revision = '9966fd8817c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_document', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
