"""Add qr_code_path to IssuedDocument

Revision ID: 9966fd8817c6
Revises: 
Create Date: 2025-08-07 12:00:36.375222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9966fd8817c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_document', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')

    # ### end Alembic commands ###
