"""Add wallet address to User

Revision ID: ec5dabed590a
Revises: df96c66b6177
Create Date: 2025-08-15 20:06:23.959084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5dabed590a'
down_revision = 'df96c66b6177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_wallet_address', ['wallet_address'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wallet_address')

    # ### end Alembic commands ###
